Algoritmo "Exercicio A - Para"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Prado
// Data atual  : 09/09/2021
Var
   // Seção de Declarações das variáveis
   x: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para x de 15 ate 200 passo 1 faca
      escreval (x, " = ", x*x)
   fimpara

Fimalgoritmo