Algoritmo "Exercicio C - Para"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Prado
// Data atual  : 09/09/2021
Var
   // Seção de Declarações das variáveis
   x,num: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para x de 1 ate 100 passo 1 faca
      escreval ("A soma)
   fimpara

Fimalgoritmo