Algoritmo "Exercicio B - Para"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Prado
// Data atual  : 09/09/2021
Var
   // Seção de Declarações das variáveis
   x,num: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval ("digite um numero")
   leia(num)
   para x de 0 ate 10 passo 1 faca
      escreval (x, " = ", x*num)
   fimpara

Fimalgoritmo