Algoritmo "D"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Prado
// Data atual  : 03/09/2021
Var
   // Seção de Declarações das variáveis
   cont:inteiro



Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


   enquanto cont <=20 faca


      se cont%2=1 entao
         Escreval("O valor ",cont," é ímpar")
      fimse
      cont<-cont+1


   fimenquanto
Fimalgoritmo