Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/08/2021
Var
// Seção de Declarações das variáveis 
final,valor_f: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Escreval("Digite o valor em graus Fahrenheit:")
  Leia (valor_f)
  final<-((valor_f-32)/9)*5
  Escreval("A temperatura em celsius é", final)

Fimalgoritmo