Algoritmo "Exercicio17"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Prado
// Data atual  : 30/08/2021
Var
   // Seção de Declarações das variáveis
   valor: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite um valor:")
   Leia (Valor)
   se valor>10 entao
      Escreval("É maior que 10")
   senao
      Escreval ("Nao é maior que 10")
   fimse
Fimalgoritmo